
DROP TABLE IF EXISTS QRTZ_TASKS;
DROP TABLE IF EXISTS QRTZ_TASKS_HISORY;


--TASK执行情况
CREATE TABLE QRTZ_TASKS (
id      INT(11) NOT NULL AUTO_INCREMENT,   
SCHED_NAME VARCHAR(120) NOT NULL,
JOB_NAME VARCHAR(200) NOT NULL,
JOB_GROUP VARCHAR(200) NOT NULL,
BEGIN_TIME TIMESTAMP NOT NULL,
STOP_TIME TIMESTAMP NULL,
IP_ADDRESS VARCHAR(16) NULL,
MAC_ADDRESS VARCHAR(12) NULL,
RESULT INT(1) NULL,
MESSAGE VARCHAR(200) NULL,
PRIMARY KEY (id))
ENGINE=INNODB;



--TASK执行历史
CREATE TABLE QRTZ_TASKS_HISORY (
SCHED_NAME VARCHAR(120) NOT NULL,
LOCK_NAME VARCHAR(40) NOT NULL,
PRIMARY KEY (SCHED_NAME,LOCK_NAME))
ENGINE=INNODB;

COMMIT; 
